[[redirects]]
  from = "/*"
  to = "https://pankesh.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/"
  to = "https://pankesh.com"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
